# Generated by Django 2.1.7 on 2019-03-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
