# Generated by Django 2.1.7 on 2019-03-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('district', models.CharField(max_length=20, null=True, verbose_name='县')),
                ('zone', models.CharField(max_length=20, null=True, verbose_name='区')),
                ('garden', models.CharField(max_length=15, null=True, verbose_name='小区')),
                ('architecture', models.CharField(max_length=20, null=True, verbose_name='版型')),
                ('property_fee', models.CharField(max_length=15, null=True, verbose_name='物业费')),
                ('property_company', models.CharField(max_length=30, null=True, verbose_name='物业公司')),
                ('developer', models.CharField(max_length=20, null=True, verbose_name='开发商')),
                ('average_price', models.IntegerField(verbose_name='小区均价')),
                ('on_sale', models.IntegerField(verbose_name='在售房数量')),
                ('description', models.CharField(default='暂无该房源的描述', max_length=50, null=True, verbose_name='房子描述')),
                ('layout', models.CharField(default='此房暂时不在售', max_length=10, null=True, verbose_name='房型')),
                ('layer', models.CharField(default='暂无楼层信息', max_length=20, null=True, verbose_name='楼层')),
                ('built_year', models.CharField(default='年份未知', max_length=8, null=True, verbose_name='建造年份')),
                ('area', models.DecimalField(decimal_places=1, default=0.0, max_digits=10, null=True, verbose_name='住房面积')),
                ('price', models.DecimalField(decimal_places=1, default=0.0, max_digits=10, null=True, verbose_name='住房单价')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=13, null=True, verbose_name='房屋总价')),
                ('orientation', models.CharField(default='暂无朝向信息', max_length=8, null=True, verbose_name='朝向')),
                ('source_url', models.CharField(default='暂无来源', max_length=40, null=True, verbose_name='数据源')),
            ],
            options={
                'verbose_name': '住房',
                'verbose_name_plural': '住房',
                'db_table': 'House',
            },
        ),
    ]
