# Generated by Django 2.1.7 on 2019-03-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='source_url',
            field=models.CharField(default='暂无来源', max_length=80, null=True, verbose_name='数据源'),
        ),
    ]
