# Generated by Django 2.1.7 on 2019-03-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20190305_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='architecture',
            field=models.CharField(max_length=30, null=True, verbose_name='版型'),
        ),
        migrations.AlterField(
            model_name='house',
            name='garden',
            field=models.CharField(max_length=40, null=True, verbose_name='小区'),
        ),
        migrations.AlterField(
            model_name='house',
            name='layer',
            field=models.CharField(default='暂无楼层信息', max_length=30, null=True, verbose_name='楼层'),
        ),
        migrations.AlterField(
            model_name='house',
            name='layout',
            field=models.CharField(default='此房暂时不在售', max_length=20, null=True, verbose_name='房型'),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_fee',
            field=models.CharField(max_length=30, null=True, verbose_name='物业费'),
        ),
        migrations.AlterField(
            model_name='house',
            name='source_url',
            field=models.CharField(default='暂无来源', max_length=100, null=True, verbose_name='数据源'),
        ),
    ]
