# Generated by Django 2.1.7 on 2019-03-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20190305_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10, verbose_name='地点')),
                ('year', models.CharField(max_length=8, verbose_name='房价年份')),
                ('month', models.CharField(max_length=4, verbose_name='房价月份')),
                ('average_price', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='均价')),
                ('tendency', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='增长比')),
            ],
            options={
                'verbose_name': '历史房均价',
                'verbose_name_plural': '历史房均价',
                'db_table': 'HistoryPrice',
            },
        ),
    ]
