# Generated by Django 2.1.7 on 2019-03-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_historyprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyprice',
            name='location',
            field=models.CharField(max_length=20, verbose_name='地点'),
        ),
    ]
