# Generated by Django 2.1.7 on 2019-03-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20190309_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyprice',
            name='location',
            field=models.CharField(max_length=30, verbose_name='地点'),
        ),
    ]
