# Generated by Django 2.1.7 on 2019-03-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20190309_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='agent_contact',
            field=models.CharField(max_length=20, null=True, verbose_name='经纪人联系方式'),
        ),
        migrations.AddField(
            model_name='house',
            name='agent_name',
            field=models.CharField(max_length=5, null=True, verbose_name='经纪人'),
        ),
        migrations.AddField(
            model_name='house',
            name='detail',
            field=models.CharField(max_length=300, null=True, verbose_name='详细信息'),
        ),
        migrations.AddField(
            model_name='house',
            name='layout_img_url',
            field=models.URLField(max_length=100, null=True, verbose_name='户型图片URL'),
        ),
        migrations.AddField(
            model_name='house',
            name='pic_url',
            field=models.URLField(max_length=100, null=True, verbose_name='图片URL'),
        ),
        migrations.AddField(
            model_name='house',
            name='visit_frequency',
            field=models.CharField(max_length=50, null=True, verbose_name='看房频率'),
        ),
    ]
