# Generated by Django 2.1.7 on 2019-03-21 03:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20190316_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10, verbose_name='城市')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='新闻标题')),
                ('body', tinymce.models.HTMLField(blank=True, verbose_name='新闻内容')),
                ('source', models.CharField(max_length=20, verbose_name='新闻来源')),
            ],
        ),
    ]
