# Generated by Django 2.1.7 on 2019-03-21 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
        migrations.AddField(
            model_name='news',
            name='add_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='发布时间'),
        ),
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
    ]
