<template>
	<div style="width: 100%; height:800px; min-width:1320px; margin-top: 60px;">
		<span class="demonstration" style="font-size: 18px;">请选择你所在的城市</span>
		<el-cascader placeholder="试试搜索：城市" @change="handleChange" v-model="optionSelect" :options="options" filterable style="margin-left: 60px;"></el-cascader>
	</div>
</template>

<script>
	import store from '@/store'
	export default {
		//省、市联动选择框数据
		data() {
			return {
				options: [{
						value: 'beijing',
						label: '北京',
						children: [{
							value: 'beijingshi',
							label: '北京市'
						}]
					},
					{
						value: 'shanghai',
						label: '上海',
						children: [{
							value: 'shanghaishi',
							label: '上海市'
						}]
					},
					{
						value: 'chongqing',
						label: '重庆',
						children: [{
							value: 'chongqingshi',
							label: '重庆市'
						}]
					},
					{
						value: 'tianjin',
						label: '天津',
						children: [{
							value: 'tianjinshi',
							label: '天津市'
						}]
					},
					{
						value: 'jiangsu',
						label: '江苏',
						children: [{
							value: 'changzhou',
							label: '常州'
						}, {
							value: 'dafeng',
							label: '大丰'
						}, {
							value: 'huaian',
							label: '淮安'
						}, {
							value: 'kunshan',
							label: '昆山'
						}, {
							value: 'lianyungang',
							label: '连云港'
						}, {
							value: 'nanjing',
							label: '南京'
						}, {
							value: 'nantong',
							label: '南通'
						}, {
							value: 'shuyang',
							label: '沭阳'
						}, {
							value: 'suqian',
							label: '宿迁'
						}, {
							value: 'suzhou',
							label: '苏州'
						}, {
							value: 'taicang',
							label: '太仓'
						}, {
							value: 'taizhou',
							label: '泰州'
						}, {
							value: 'wuxi',
							label: '无锡'
						}, {
							value: 'xuzhou',
							label: '徐州'
						}, {
							value: 'yancheng',
							label: '盐城'
						}, {
							value: 'yangzhou',
							label: '扬州'
						}, {
							value: 'zhenjiang',
							label: '镇江'
						}, ]
					},
					{
						value: 'zhejiang',
						label: '浙江',
						children: [{
							value: 'hangzhou',
							label: '杭州'
						}, {
							value: 'huzhou',
							label: '湖州'
						}, {
							value: 'jiaxing',
							label: '嘉兴'
						}, {
							value: 'jinhua',
							label: '金华'
						}, {
							value: 'lishui',
							label: '丽水'
						}, {
							value: 'ningbo',
							label: '宁波'
						}, {
							value: 'quzhou',
							label: '衢州'
						}, {
							value: 'ruian',
							label: '瑞安'
						}, {
							value: 'shaoxing',
							label: '绍兴'
						}, {
							value: 'taizhou',
							label: '台州'
						}, {
							value: 'wenzhou',
							label: '温州'
						}, {
							value: 'yiwu',
							label: '义乌'
						}, {
							value: 'leqing',
							label: '乐清'
						}, {
							value: 'zhoushan',
							label: '舟山'
						}, ]
					},
					{
						value: 'guangxi',
						label: '广西',
						children: [{
							value: 'baise',
							label: '百色'
						}, {
							value: 'beihai',
							label: '北海'
						}, {
							value: 'chongzuo',
							label: '崇左'
						}, {
							value: 'fangchenggang',
							label: '防城港'
						}, {
							value: 'guigang',
							label: '贵港'
						}, {
							value: 'guilin',
							label: '桂林'
						}, {
							value: 'hechi',
							label: '河池'
						}, {
							value: 'hezhou',
							label: '贺州'
						}, {
							value: 'laibin',
							label: '来宾'
						}, {
							value: 'liuzhou',
							label: '柳州'
						}, {
							value: 'nanning',
							label: '南宁'
						}, {
							value: 'qinzhou',
							label: '钦州'
						}, {
							value: 'wuzhou',
							label: '梧州'
						}, {
							value: 'yulin',
							label: '玉林'
						}, ]
					},
					{
						value: 'hebei',
						label: '河北',
						children: [{
							value: 'baoding',
							label: '保定'
						}, {
							value: 'cangzhou',
							label: '沧州'
						}, {
							value: 'chengde',
							label: '承德'
						}, {
							value: 'dingzhou',
							label: '定州'
						}, {
							value: 'guantao',
							label: '馆陶'
						}, {
							value: 'handan',
							label: '邯郸'
						}, {
							value: 'hengshui',
							label: '衡水'
						}, {
							value: 'langfang',
							label: '廊坊'
						}, {
							value: 'qinhuangdao',
							label: '秦皇岛'
						}, {
							value: 'shijiazhuang',
							label: '石家庄'
						}, {
							value: 'tangshan',
							label: '唐山'
						}, {
							value: 'xingtai',
							label: '邢台'
						}, {
							value: 'zhangbei',
							label: '张北'
						}, {
							value: 'zhangjiakou',
							label: '张家口'
						}, {
							value: 'zhaoxian',
							label: '赵县'
						}, {
							value: 'zhengding',
							label: '正定'
						}, ]
					},
					{
						value: 'henan',
						label: '河南',
						children: [{
							value: 'anyang',
							label: '安阳'
						}, {
							value: 'changge',
							label: '长葛'
						}, {
							value: 'hebi',
							label: '鹤壁'
						}, {
							value: 'jiaozuo',
							label: '焦作'
						}, {
							value: 'jiyuan',
							label: '济源'
						}, {
							value: 'kaifeng',
							label: '开封'
						}, {
							value: 'tahe',
							label: '漯河'
						}, {
							value: 'luoyang',
							label: '洛阳'
						}, {
							value: 'minggang',
							label: '明港'
						}, {
							value: 'nanyang',
							label: '南阳'
						}, {
							value: 'pingdingshan',
							label: '平顶山'
						}, {
							value: 'puyang',
							label: '濮阳'
						}, {
							value: 'sanmenxia',
							label: '三门峡'
						}, {
							value: 'shangqiu',
							label: '商丘'
						}, {
							value: 'xinxiang',
							label: '新乡'
						}, {
							value: 'xinyang',
							label: '信阳'
						}, {
							value: 'xuchang',
							label: '许昌'
						}, {
							value: 'yanling',
							label: '鄢陵'
						}, {
							value: 'yuzhou',
							label: '禹州'
						}, {
							value: 'zhengzhou',
							label: '郑州'
						}, {
							value: 'zhoukou',
							label: '周口'
						}, {
							value: 'zhumadian',
							label: '驻马店'
						}, ]
					},
					{
						value: 'hubei',
						label: '湖北',
						children: [{
							value: 'enshi',
							label: '恩施'
						}, {
							value: 'ezhou',
							label: '鄂州'
						}, {
							value: 'huanggang',
							label: '黄冈'
						}, {
							value: 'huangshi',
							label: '黄石'
						}, {
							value: 'jingmen',
							label: '荆门'
						}, {
							value: 'jingzhou',
							label: '荆州'
						}, {
							value: 'qianjiang',
							label: '潜江'
						}, {
							value: 'shennongjia',
							label: '神农架'
						}, {
							value: 'shiyan',
							label: '十堰'
						}, {
							value: 'suizhou',
							label: '随州'
						}, {
							value: 'tianmen',
							label: '天门'
						}, {
							value: 'wuhan',
							label: '武汉'
						}, {
							value: 'xiangyang',
							label: '襄阳'
						}, {
							value: 'xianning',
							label: '咸宁'
						}, {
							value: 'xiantao',
							label: '仙桃'
						}, {
							value: 'xiaogan',
							label: '孝感'
						}, {
							value: 'yichang',
							label: '宜昌'
						}, ]
					},
					{
						value: 'hunan',
						label: '湖南',
						children: [{
							value: 'changde',
							label: '常德'
						}, {
							value: 'changsha',
							label: '长沙'
						}, {
							value: 'chenzhou',
							label: '郴州'
						}, {
							value: 'hengyang',
							label: '衡阳'
						}, {
							value: 'huaihua',
							label: '怀化'
						}, {
							value: 'loudi',
							label: '娄底'
						}, {
							value: 'shaoyang',
							label: '邵阳'
						}, {
							value: 'xiangtan',
							label: '湘潭'
						}, {
							value: 'xiangxi',
							label: '湘西'
						}, {
							value: 'yiyang',
							label: '益阳'
						}, {
							value: 'yongzhou',
							label: '永州'
						}, {
							value: 'yueyang',
							label: '岳阳'
						}, {
							value: 'zhangjiajie',
							label: '张家界'
						}, {
							value: 'zhuzhou',
							label: '株洲'
						}, ]
					},
					{
						value: 'gansu',
						label: '甘肃',
						children: [{
							value: 'baiyin',
							label: '白银'
						}, {
							value: 'dingxi',
							label: '定西'
						}, {
							value: 'gannan',
							label: '甘南'
						}, {
							value: 'jiayuguan',
							label: '嘉峪关'
						}, {
							value: 'jinchang',
							label: '金昌'
						}, {
							value: 'jiuquan',
							label: '酒泉'
						}, {
							value: 'lanzhou',
							label: '兰州'
						}, {
							value: 'linxia',
							label: '临夏'
						}, {
							value: 'longnan',
							label: '陇南'
						}, {
							value: 'pingliang',
							label: '平凉'
						}, {
							value: 'qingyang',
							label: '庆阳'
						}, {
							value: 'tianshui',
							label: '天水'
						}, {
							value: 'wuwei',
							label: '武威'
						}, {
							value: 'zhangye',
							label: '张掖'
						}, ]
					},
					{
						value: 'fujian',
						label: '福建',
						children: [{
							value: 'fuzhou',
							label: '福州'
						}, {
							value: 'longyan',
							label: '龙岩'
						}, {
							value: 'nanping',
							label: '南平'
						}, {
							value: 'ningde',
							label: '宁德'
						}, {
							value: 'futian',
							label: '莆田'
						}, {
							value: 'quanzhou',
							label: '泉州'
						}, {
							value: 'sanming',
							label: '三明'
						}, {
							value: 'wuyishan',
							label: '武夷山'
						}, {
							value: 'shamen',
							label: '厦门'
						}, {
							value: 'zhangzhou',
							label: '漳州'
						}, ]
					},
					{
						value: 'guizhou',
						label: '贵州',
						children: [{
							value: 'anshun',
							label: '安顺'
						}, {
							value: 'bijie',
							label: '毕节'
						}, {
							value: 'guiyang',
							label: '贵阳'
						}, {
							value: 'liupanshui',
							label: '六盘水'
						}, {
							value: 'qiandongnan',
							label: '黔东南'
						}, {
							value: 'qiannan',
							label: '黔南'
						}, {
							value: 'qianxinan',
							label: '黔西南'
						}, {
							value: 'tongren',
							label: '铜仁'
						}, {
							value: 'zunyi',
							label: '遵义'
						}, ]
					},
					{
						value: 'heilongjiang',
						label: '黑龙江',
						children: [{
							value: 'daqing',
							label: '大庆'
						}, {
							value: 'daxinganling',
							label: '大兴安岭'
						}, {
							value: 'haerbin',
							label: '哈尔滨'
						}, {
							value: 'hegang',
							label: '鹤岗'
						}, {
							value: 'heihe',
							label: '黑河'
						}, {
							value: 'jiamusi',
							label: '佳木斯'
						}, {
							value: 'jixi',
							label: '鸡西'
						}, {
							value: 'mudanjiang',
							label: '牡丹江'
						}, {
							value: 'qiqihaer',
							label: '齐齐哈尔'
						}, {
							value: 'qitaihe',
							label: '七台河'
						}, {
							value: 'shuangyashan',
							label: '双鸭山'
						}, {
							value: 'suihua',
							label: '绥化'
						}, {
							value: 'yichun',
							label: '伊春'
						}, ]
					},
					{
						value: 'anhui',
						label: '安徽',
						children: [{
							value: 'anqing',
							label: '安庆'
						}, {
							value: 'bangbu',
							label: '蚌埠'
						}, {
							value: 'bozhou',
							label: '亳州'
						}, {
							value: 'chaohu',
							label: '巢湖'
						}, {
							value: 'chizhou',
							label: '池州'
						}, {
							value: 'chuzhou',
							label: '滁州'
						}, {
							value: 'fuyang',
							label: '阜阳'
						}, {
							value: 'hefei',
							label: '合肥'
						}, {
							value: 'hexian',
							label: '和县'
						}, {
							value: 'huoqiu',
							label: '霍邱'
						}, {
							value: 'huaibei',
							label: '淮北'
						}, {
							value: 'huainan',
							label: '淮南'
						}, {
							value: 'huangshan',
							label: '黄山'
						}, {
							value: 'liuan',
							label: '六安'
						}, {
							value: 'maanshan',
							label: '马鞍山'
						}, {
							value: 'suzhou',
							label: '宿州'
						}, {
							value: 'tongcheng',
							label: '桐城'
						}, {
							value: 'tongling',
							label: '铜陵'
						}, {
							value: 'wuhu',
							label: '芜湖'
						}, {
							value: 'xuancheng',
							label: '宣城'
						}, ]
					},
					{
						value: 'yunnan',
						label: '云南',
						children: [{
							value: 'xishuangbanna',
							label: '西双版纳'
						}, {
							value: 'baoshan',
							label: '保山'
						}, {
							value: 'chuxiong',
							label: '楚雄'
						}, {
							value: 'dali',
							label: '大理'
						}, {
							value: 'dehong',
							label: '德宏'
						}, {
							value: 'diqing',
							label: '迪庆'
						}, {
							value: 'honghe',
							label: '红河'
						}, {
							value: 'kunming',
							label: '昆明'
						}, {
							value: 'lijiang',
							label: '丽江'
						}, {
							value: 'lincang',
							label: '临沧'
						}, {
							value: 'nujiang',
							label: '怒江'
						}, {
							value: 'puer',
							label: '普洱'
						}, {
							value: 'qujing',
							label: '曲靖'
						}, {
							value: 'wenshan',
							label: '文山'
						}, {
							value: 'yuxi',
							label: '玉溪'
						}, {
							value: 'zhaotong',
							label: '昭通'
						}, ]
					},
					{
						value: 'neimenggu',
						label: '内蒙古',
						children: [{
							value: 'alashanmeng',
							label: '阿拉善盟'
						}, {
							value: 'baotou',
							label: '包头'
						}, {
							value: 'bayannaoershi',
							label: '巴彦淖尔市'
						}, {
							value: 'chifeng',
							label: '赤峰'
						}, {
							value: 'eerduosi',
							label: '鄂尔多斯'
						}, {
							value: 'hailaer',
							label: '海拉尔'
						}, {
							value: 'huhehaote',
							label: '呼和浩特'
						}, {
							value: 'hulunbeier',
							label: '呼伦贝尔'
						}, {
							value: 'tongliao',
							label: '通辽'
						}, {
							value: 'wuhai',
							label: '乌海'
						}, {
							value: 'wulanchabu',
							label: '乌兰察布'
						}, {
							value: 'xilinguolemeng',
							label: '锡林郭勒盟'
						}, {
							value: 'xinganmeng',
							label: '兴安盟'
						}, ]
					},
					{
						value: 'jilin',
						label: '吉林',
						children: [{
							value: 'yongji',
							label: '永吉'
						}, {
							value: 'shulan',
							label: '舒兰'
						}, {
							value: 'panshi',
							label: '磐石'
						}, {
							value: 'jiaohe',
							label: '蛟河'
						}, {
							value: 'huadian',
							label: '桦甸'
						}, {
							value: 'jilinzhoubian',
							label: '吉林周边'
						}, {
							value: 'chuanying',
							label: '船营'
						}, {
							value: 'changyi',
							label: '昌邑'
						}, {
							value: 'fengman',
							label: '丰满'
						}, {
							value: 'longtan',
							label: '龙潭'
						}, {
							value: 'gaoxin',
							label: '高新'
						}, {
							value: 'jingkai',
							label: '经开'
						}, ]
					},
					{
						value: 'sichuan',
						label: '四川',
						children: [{
							value: 'aba',
							label: '阿坝'
						}, {
							value: 'bazhong',
							label: '巴中'
						}, {
							value: 'chengdu',
							label: '成都'
						}, {
							value: 'dazhou',
							label: '达州'
						}, {
							value: 'deyang',
							label: '德阳'
						}, {
							value: 'guangyuan',
							label: '广元'
						}, {
							value: 'ganzi',
							label: '甘孜'
						}, {
							value: 'guangan',
							label: '广安'
						}, {
							value: 'leshan',
							label: '乐山'
						}, {
							value: 'liangshan',
							label: '凉山'
						}, {
							value: 'luzhou',
							label: '泸州'
						}, {
							value: 'meishan',
							label: '眉山'
						}, {
							value: 'mianyang',
							label: '绵阳'
						}, {
							value: 'nanchong',
							label: '南充'
						}, {
							value: 'neijiang',
							label: '内江'
						}, {
							value: 'panzhihua',
							label: '攀枝花'
						}, {
							value: 'suining',
							label: '遂宁'
						}, {
							value: 'yaan',
							label: '雅安'
						}, {
							value: 'yibin',
							label: '宜宾'
						}, {
							value: 'zigong',
							label: '自贡'
						}, {
							value: 'ziyang',
							label: '资阳'
						}, ]
					},
					{
						value: 'ningxia',
						label: '宁夏',
						children: [{
							value: 'guyuan',
							label: '固原'
						}, {
							value: 'shizuishan',
							label: '石嘴山'
						}, {
							value: 'zhongwei',
							label: '中卫'
						}, {
							value: 'wuzhong',
							label: '吴忠'
						}, {
							value: 'yinchuan',
							label: '银川'
						}, ]
					},
					{
						value: 'shandong',
						label: '山东',
						children: [{
							value: 'binzhou',
							label: '滨州'
						}, {
							value: 'dezhou',
							label: '德州'
						}, {
							value: 'dongying',
							label: '东营'
						}, {
							value: 'heze',
							label: '菏泽'
						}, {
							value: 'jinan',
							label: '济南'
						}, {
							value: 'jining',
							label: '济宁'
						}, {
							value: 'kenli',
							label: '垦利'
						}, {
							value: 'laiwu',
							label: '莱芜'
						}, {
							value: 'liaocheng',
							label: '聊城'
						}, {
							value: 'linyi',
							label: '临沂'
						}, {
							value: 'qingdao',
							label: '青岛'
						}, {
							value: 'rizhao',
							label: '日照'
						}, {
							value: 'taian',
							label: '泰安'
						}, {
							value: 'weifang',
							label: '潍坊'
						}, {
							value: 'weihai',
							label: '威海'
						}, {
							value: 'yantai',
							label: '烟台'
						}, {
							value: 'zaozhuang',
							label: '枣庄'
						}, {
							value: 'zhangqiu',
							label: '章丘'
						}, {
							value: 'zhucheng',
							label: '诸城'
						}, {
							value: 'zibo',
							label: '淄博'
						}, ]
					},
					{
						value: 'shanxi',
						label: '山西',
						children: [{
							value: 'changzhi',
							label: '长治'
						}, {
							value: 'datong',
							label: '大同'
						}, {
							value: 'jincheng',
							label: '晋城'
						}, {
							value: 'jinzhong',
							label: '晋中'
						}, {
							value: 'linfen',
							label: '临汾'
						}, {
							value: 'linyi',
							label: '临猗'
						}, {
							value: 'lvliang',
							label: '吕梁'
						}, {
							value: 'qingxu',
							label: '清徐'
						}, {
							value: 'shuozhou',
							label: '朔州'
						}, {
							value: 'taiyuan',
							label: '太原'
						}, {
							value: 'xinzhou',
							label: '忻州'
						}, {
							value: 'yangquan',
							label: '阳泉'
						}, {
							value: 'yuncheng',
							label: '运城'
						}, ]
					},
					{
						value: 'xinjiang',
						label: '新疆',
						children: [{
							value: 'akesu',
							label: '阿克苏'
						}, {
							value: 'alaer',
							label: '阿拉尔'
						}, {
							value: 'bayinguoleng',
							label: '巴音郭楞'
						}, {
							value: 'boertala',
							label: '博尔塔拉'
						}, {
							value: 'changji',
							label: '昌吉'
						}, {
							value: 'hami',
							label: '哈密'
						}, {
							value: 'hetian',
							label: '和田'
						}, {
							value: 'kashen',
							label: '喀什'
						}, {
							value: 'kelamayi',
							label: '克拉玛依'
						}, {
							value: 'kezilesu',
							label: '克孜勒苏'
						}, {
							value: 'shihezi',
							label: '石河子'
						}, {
							value: 'tulufan',
							label: '吐鲁番'
						}, {
							value: 'tumushuke',
							label: '图木舒克'
						}, {
							value: 'wujiaqu',
							label: '五家渠'
						}, {
							value: 'wulumuqi',
							label: '乌鲁木齐'
						}, {
							value: 'yili',
							label: '伊犁'
						}, ]
					},
					{
						value: 'jiangxi',
						label: '江西',
						children: [{
							value: 'fuzhou',
							label: '抚州'
						}, {
							value: 'ganzhou',
							label: '赣州'
						}, {
							value: 'jian',
							label: '吉安'
						}, {
							value: 'jingdezhen',
							label: '景德镇'
						}, {
							value: 'jiujiang',
							label: '九江'
						}, {
							value: 'nanchang',
							label: '南昌'
						}, {
							value: 'pingxiang',
							label: '萍乡'
						}, {
							value: 'shangrao',
							label: '上饶'
						}, {
							value: 'xinyu',
							label: '新余'
						}, {
							value: 'yichun',
							label: '宜春'
						}, {
							value: 'yingtan',
							label: '鹰潭'
						}, {
							value: 'yongxin',
							label: '永新'
						}, ]
					},
					{
						value: 'xicang',
						label: '西藏',
						children: [{
							value: 'ali',
							label: '阿里'
						}, {
							value: 'changdu',
							label: '昌都'
						}, {
							value: 'lasa',
							label: '拉萨'
						}, {
							value: 'linzhi',
							label: '林芝'
						}, {
							value: 'naqu',
							label: '那曲'
						}, {
							value: 'rikaze',
							label: '日喀则'
						}, {
							value: 'shannan',
							label: '山南'
						}, ]
					},
					{
						value: 'liaoning',
						label: '辽宁',
						children: [{
							value: 'anshan',
							label: '鞍山'
						}, {
							value: 'benxi',
							label: '本溪'
						}, {
							value: 'zhaoyang',
							label: '朝阳'
						}, {
							value: 'dalian',
							label: '大连'
						}, {
							value: 'dandong',
							label: '丹东'
						}, {
							value: 'fushun',
							label: '抚顺'
						}, {
							value: 'fuxin',
							label: '阜新'
						}, {
							value: 'huludao',
							label: '葫芦岛'
						}, {
							value: 'jinzhou',
							label: '锦州'
						}, {
							value: 'liaoyang',
							label: '辽阳'
						}, {
							value: 'panjin',
							label: '盘锦'
						}, {
							value: 'shenyang',
							label: '沈阳'
						}, {
							value: 'tieling',
							label: '铁岭'
						}, {
							value: 'wafangdian',
							label: '瓦房店'
						}, {
							value: 'yingkou',
							label: '营口'
						}, {
							value: 'zhuanghe',
							label: '庄河'
						}, ]
					},
					{
						value: 'shanxi',
						label: '陕西',
						children: [{
							value: 'ankang',
							label: '安康'
						}, {
							value: 'baoji',
							label: '宝鸡'
						}, {
							value: 'hanzhong',
							label: '汉中'
						}, {
							value: 'shangluo',
							label: '商洛'
						}, {
							value: 'tongchuan',
							label: '铜川'
						}, {
							value: 'weinan',
							label: '渭南'
						}, {
							value: 'xian',
							label: '西安'
						}, {
							value: 'xianyang',
							label: '咸阳'
						}, {
							value: 'yanan',
							label: '延安'
						}, {
							value: 'yulin',
							label: '榆林'
						}, ]
					},
					{
						value: 'qinghai',
						label: '青海',
						children: [{
							value: 'guoluo',
							label: '果洛'
						}, {
							value: 'haibei',
							label: '海北'
						}, {
							value: 'haidong',
							label: '海东'
						}, {
							value: 'hainan',
							label: '海南'
						}, {
							value: 'haixi',
							label: '海西'
						}, {
							value: 'huangnan',
							label: '黄南'
						}, {
							value: 'xining',
							label: '西宁'
						}, {
							value: 'yushu',
							label: '玉树'
						}, ]
					},


















				],
				optionSelect: [],
			};
		},
		methods: {
			handleChange() {
				var value = this.getCascaderObj(this.optionSelect, this.options)
				console.log(value)
				var area = {}
				area["province"] = value[0].label
				area["city"] = value[1].label
				area["area"] = ''
				area["street"] = ''
				store.commit('change_AreaInfo', area)
				this.$router.go(-1)
			},
			getCascaderObj(val, opt) {
				return val.map(function(value, index, array) {
					for (var itm of opt) {
						if (itm.value == value) {
							opt = itm.children;
							return itm;
						}
					}
					return null;
				});
			}
		}
	};
</script>

<style>

</style>
